# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83062dd633e484819bb8bc951489b4adac31d8bb7936a1b9becad2863ca906ad53ab612636ef5ddeb5d79d0f2e80550abc357bab8117ace14d806d37da59ee78

test:
  secret_key_base: 2cae898e280164f9272f7f268a11296a1079296a0a0a3afd72db4c3d0fdeebbb15008e5d03387d057b01df9df41f9d24d863dca0d055ffd175a5737c3126d794

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
